### ISSUE TITLE
raising StopIteration causes a RunTime error on Python 3.8

### ISSUE THREAD

**Issue by tensorfoo** [mozilla/DSAlign#12] opened 2019-11-26 14:07 UTC
From the Python docs, 

> Changed in version 3.3: Added value attribute and the ability for generator functions to use it to return a value.
> 
> Changed in version 3.5: Introduced the RuntimeError transformation via from __future__ import generator_stop, see PEP 479.
> 
> Changed in version 3.7: Enable PEP 479 for all code by default: a StopIteration error raised in a generator is transformed into a RuntimeError.

Running into this now that i've been moving to 3.8. Seeking clarification on what the Author is trying to do here so I can patch the code on my end. I'm guessing (not a Python programmer) that we're trying to bail out of the iteration but on Python versions other than 3.6 it doesn't behave well.

> Traceback: in split_match
>     raise StopIteration
> StopIteration
> 

edit, i was able to modify the `Raise StopIteration` lines to `return` and that seems to have done the trick.

**Comment by tilmankamp** [comment] 2019-11-26 16:43
Duplicate of #4

**Closed as completed by tilmankamp** 2019-11-26 16:43 UTC
